package com.google.android.setupcompat.partnerconfig;

public enum PartnerConfig {
    CONFIG_STATUS_BAR_BACKGROUND("setup_compat_status_bar_background", r1),
    CONFIG_LIGHT_STATUS_BAR("setup_compat_light_status_bar", r4),
    CONFIG_NAVIGATION_BAR_BG_COLOR("setup_compat_navigation_bar_bg_color", r7),
    CONFIG_NAVIGATION_BAR_DIVIDER_COLOR("setup_compat_navigation_bar_divider_color", r7),
    CONFIG_FOOTER_BAR_BG_COLOR("setup_compat_footer_bar_bg_color", r7),
    CONFIG_FOOTER_BAR_MIN_HEIGHT("setup_compat_footer_bar_min_height", r14),
    CONFIG_LIGHT_NAVIGATION_BAR("setup_compat_light_navigation_bar", r4),
    CONFIG_FOOTER_BUTTON_FONT_FAMILY("setup_compat_footer_button_font_family", r15),
    CONFIG_FOOTER_BUTTON_ICON_ADD_ANOTHER("setup_compat_footer_button_icon_add_another", r1),
    CONFIG_FOOTER_BUTTON_ICON_CANCEL("setup_compat_footer_button_icon_cancel", r1),
    CONFIG_FOOTER_BUTTON_ICON_CLEAR("setup_compat_footer_button_icon_clear", r1),
    CONFIG_FOOTER_BUTTON_ICON_DONE("setup_compat_footer_button_icon_done", r1),
    CONFIG_FOOTER_BUTTON_ICON_NEXT("setup_compat_footer_button_icon_next", r1),
    CONFIG_FOOTER_BUTTON_ICON_OPT_IN("setup_compat_footer_button_icon_opt_in", r1),
    CONFIG_FOOTER_BUTTON_ICON_SKIP("setup_compat_footer_button_icon_skip", r1),
    CONFIG_FOOTER_BUTTON_ICON_STOP("setup_compat_footer_button_icon_stop", r1),
    CONFIG_FOOTER_BUTTON_PADDING_TOP("setup_compat_footer_button_padding_top", r14),
    CONFIG_FOOTER_BUTTON_PADDING_BOTTOM("setup_compat_footer_button_padding_bottom", r14),
    CONFIG_FOOTER_BUTTON_RADIUS("setup_compat_footer_button_radius", r14),
    CONFIG_FOOTER_BUTTON_RIPPLE_COLOR_ALPHA("setup_compat_footer_button_ripple_alpha", r6),
    CONFIG_FOOTER_BUTTON_TEXT_SIZE("setup_compat_footer_button_text_size", r14),
    CONFIG_FOOTER_BUTTON_TEXT_STYLE("setup_compat_footer_button_text_style", r13),
    CONFIG_FOOTER_BUTTON_MIN_HEIGHT("setup_compat_footer_button_min_height", r14),
    CONFIG_FOOTER_BUTTON_DISABLED_ALPHA("setup_compat_footer_button_disabled_alpha", r6),
    CONFIG_FOOTER_BUTTON_DISABLED_BG_COLOR("setup_compat_footer_button_disabled_bg_color", r7),
    CONFIG_FOOTER_PRIMARY_BUTTON_BG_COLOR("setup_compat_footer_primary_button_bg_color", r7),
    CONFIG_FOOTER_PRIMARY_BUTTON_TEXT_COLOR("setup_compat_footer_primary_button_text_color", r7),
    CONFIG_FOOTER_SECONDARY_BUTTON_BG_COLOR("setup_compat_footer_secondary_button_bg_color", r7),
    CONFIG_FOOTER_SECONDARY_BUTTON_TEXT_COLOR("setup_compat_footer_secondary_button_text_color", r7),
    CONFIG_LAYOUT_BACKGROUND_COLOR("setup_design_layout_bg_color", r7),
    CONFIG_LAYOUT_MARGIN_START("setup_design_layout_margin_start", r14),
    CONFIG_LAYOUT_MARGIN_END("setup_design_layout_margin_end", r14),
    CONFIG_HEADER_TEXT_COLOR("setup_design_header_text_color", r7),
    CONFIG_HEADER_TEXT_SIZE("setup_design_header_text_size", r14),
    CONFIG_HEADER_FONT_FAMILY("setup_design_header_font_family", r15),
    CONFIG_HEADER_TEXT_MARGIN_TOP("setup_design_header_text_margin_top", r14),
    CONFIG_HEADER_TEXT_MARGIN_BOTTOM("setup_design_header_text_margin_bottom", r14),
    CONFIG_LAYOUT_GRAVITY("setup_design_layout_gravity", r15),
    CONFIG_ICON_MARGIN_TOP("setup_design_icon_margin_top", r14),
    CONFIG_ICON_SIZE("setup_design_icon_size", r14),
    CONFIG_HEADER_AREA_BACKGROUND_COLOR("setup_design_header_area_background_color", r7),
    CONFIG_HEADER_CONTAINER_MARGIN_BOTTOM("setup_design_header_container_margin_bottom", r14),
    CONFIG_HEADER_AUTO_SIZE_ENABLED("setup_design_header_auto_size_enabled", r4),
    CONFIG_HEADER_AUTO_SIZE_MAX_TEXT_SIZE("setup_design_header_auto_size_max_text_size", r14),
    CONFIG_HEADER_AUTO_SIZE_MIN_TEXT_SIZE("setup_design_header_auto_size_min_text_size", r14),
    CONFIG_HEADER_AUTO_SIZE_MAX_LINE_OF_MAX_SIZE("setup_design_header_auto_size_max_line_of_max_size", r13),
    CONFIG_HEADER_AUTO_SIZE_LINE_SPACING_EXTRA("setup_design_header_auto_size_line_spacing_extra", r14),
    CONFIG_DESCRIPTION_TEXT_SIZE("setup_design_description_text_size", r14),
    CONFIG_DESCRIPTION_TEXT_COLOR("setup_design_description_text_color", r7),
    CONFIG_DESCRIPTION_LINK_TEXT_COLOR("setup_design_description_link_text_color", r7),
    CONFIG_DESCRIPTION_FONT_FAMILY("setup_design_description_font_family", r15),
    CONFIG_DESCRIPTION_TEXT_MARGIN_TOP("setup_design_description_text_margin_top", r14),
    CONFIG_DESCRIPTION_TEXT_MARGIN_BOTTOM("setup_design_description_text_margin_bottom", r14),
    CONFIG_CONTENT_TEXT_SIZE("setup_design_content_text_size", r14),
    CONFIG_CONTENT_TEXT_COLOR("setup_design_content_text_color", r7),
    CONFIG_CONTENT_LINK_TEXT_COLOR("setup_design_content_link_text_color", r7),
    CONFIG_CONTENT_FONT_FAMILY("setup_design_content_font_family", r15),
    CONFIG_CONTENT_LAYOUT_GRAVITY("setup_design_content_layout_gravity", r15),
    CONFIG_CONTENT_PADDING_TOP("setup_design_content_padding_top", r14),
    CONFIG_CONTENT_INFO_TEXT_SIZE("setup_design_content_info_text_size", r14),
    CONFIG_CONTENT_INFO_FONT_FAMILY("setup_design_content_info_font_family", r15),
    CONFIG_CONTENT_INFO_LINE_SPACING_EXTRA("setup_design_content_info_line_spacing_extra", r14),
    CONFIG_CONTENT_INFO_ICON_SIZE("setup_design_content_info_icon_size", r14),
    CONFIG_CONTENT_INFO_ICON_MARGIN_END("setup_design_content_info_icon_margin_end", r14),
    CONFIG_CONTENT_INFO_PADDING_TOP("setup_design_content_info_padding_top", r14),
    CONFIG_CONTENT_INFO_PADDING_BOTTOM("setup_design_content_info_padding_bottom", r14),
    CONFIG_ITEMS_TITLE_TEXT_SIZE("setup_design_items_title_text_size", r14),
    CONFIG_ITEMS_SUMMARY_TEXT_SIZE("setup_design_items_summary_text_size", r14),
    CONFIG_ITEMS_SUMMARY_MARGIN_TOP("setup_design_items_summary_margin_top", r14),
    CONFIG_ITEMS_TITLE_FONT_FAMILY("setup_design_items_title_font_family", r15),
    CONFIG_ITEMS_SUMMARY_FONT_FAMILY("setup_design_items_summary_font_family", r15),
    CONFIG_ITEMS_PADDING_TOP("setup_design_items_padding_top", r14),
    CONFIG_ITEMS_PADDING_BOTTOM("setup_design_items_padding_bottom", r14),
    CONFIG_ITEMS_MIN_HEIGHT("setup_design_items_min_height", r14),
    CONFIG_ITEMS_DIVIDER_SHOWN("setup_design_items_divider_shown", r4),
    CONFIG_PROGRESS_ILLUSTRATION_DEFAULT("progress_illustration_custom_default", r7),
    CONFIG_PROGRESS_ILLUSTRATION_ACCOUNT("progress_illustration_custom_account", r7),
    CONFIG_PROGRESS_ILLUSTRATION_CONNECTION("progress_illustration_custom_connection", r7),
    CONFIG_PROGRESS_ILLUSTRATION_UPDATE("progress_illustration_custom_update", r7),
    CONFIG_PROGRESS_ILLUSTRATION_FINAL_HOLD("final_hold_custom_illustration", r7),
    CONFIG_PROGRESS_ILLUSTRATION_DISPLAY_MINIMUM_MS("progress_illustration_display_minimum_ms", r13),
    CONFIG_LOADING_LOTTIE_DEFAULT("loading_animation_custom_default", r7),
    CONFIG_LOADING_LOTTIE_ACCOUNT("loading_animation_custom_account", r7),
    CONFIG_LOADING_LOTTIE_CONNECTION("loading_animation_custom_connection", r7),
    CONFIG_LOADING_LOTTIE_UPDATE("loading_animation_custom_update", r7),
    CONFIG_LOADING_LOTTIE_FINAL_HOLD("loading_animation_custom_final_hold", r7),
    CONFIG_TRANSITION_TYPE("setup_design_transition_type", r13),
    CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_DEFAULT("loading_light_theme_customization_default", r11),
    CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_ACCOUNT("loading_light_theme_customization_account", r11),
    CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_CONNECTION("loading_light_theme_customization_connection", r11),
    CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_UPDATE("loading_light_theme_customization_update", r11),
    CONFIG_LOTTIE_LIGHT_THEME_CUSTOMIZATION_FINAL_HOLD("loading_light_theme_customization_final_hold", r11),
    CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_DEFAULT("loading_dark_theme_customization_default", r11),
    CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_ACCOUNT("loading_dark_theme_customization_account", r11),
    CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_CONNECTION("loading_dark_theme_customization_connection", r11),
    CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_UPDATE("loading_dark_theme_customization_update", r11),
    CONFIG_LOTTIE_DARK_THEME_CUSTOMIZATION_FINAL_HOLD("loading_dark_theme_customization_final_hold", r11),
    CONFIG_LOADING_LAYOUT_PADDING_TOP("loading_layout_content_padding_top", r14),
    CONFIG_LOADING_LAYOUT_PADDING_START("loading_layout_content_padding_start", r14),
    CONFIG_LOADING_LAYOUT_PADDING_END("loading_layout_content_padding_end", r14),
    CONFIG_LOADING_LAYOUT_PADDING_BOTTOM("loading_layout_content_padding_bottom", r14),
    CONFIG_LOADING_LAYOUT_HEADER_HEIGHT("loading_layout_header_height", r14);
    
    private final String resourceName;
    private final ResourceType resourceType;

    public enum ResourceType {
        INTEGER,
        BOOL,
        COLOR,
        DRAWABLE,
        STRING,
        DIMENSION,
        FRACTION,
        ILLUSTRATION,
        STRING_ARRAY
    }

    public ResourceType getResourceType() {
        return this.resourceType;
    }

    public String getResourceName() {
        return this.resourceName;
    }

    private PartnerConfig(String str, ResourceType resourceType2) {
        this.resourceName = str;
        this.resourceType = resourceType2;
    }
}
